export const rolesData = [
  { 
    name: 'Werewolf', 
    key: 'werewolf', 
    color: '#832727', 
    ability: 'Werewolves take human form during the day, doing their best Town Resident impression. When the moon rises, the pack embraces their true form and hunts one victim each night.', 
    winCondition: 'Ravage town to match its population.', 
    reminder: 'nightly', 
    assigned: 0, 
    expansionRole: false, 
    enabled: true, 
    images: ["werewolf-both"], 
  },
  
  { 
    name: 'Town Resident', 
    key: 'town-resident', 
    color: '#E4A685', 
    ability: "Town Residents are eager to help despite always getting picked last. They may not be the best at fighting werewolves... <span>but if you need 'em, they can vote.</span>", 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: null, 
    assigned: 0, 
    expansionRole: false, 
    enabled: true, 
    images: ["town_resident-male", "town_resident-female"], 
  },
  
  { 
    name: 'Sheriff', 
    key: 'sheriff', 
    color: '#EBB663', 
    ability: "Sworn to serve, the Sheriff investigates one player each night.  While they learn if the player is a werewolf, other specifics are elusive.", 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: 'nightly', 
    assigned: false, 
    expansionRole: false, 
    enabled: true, 
    images: ["sheriff-male", "sheriff-female"], 
  },
  
  { 
    name: 'Doctor', 
    key: 'doctor', 
    color: '#79D0E4', 
    ability: 'The town Doctor takes a hippocratic oath to save one player each night. If successful, they must choose a new patient next time.', 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: 'nightly', lastSavedPlayer: null, 
    assigned: false, 
    expansionRole: false, 
    enabled: true, 
    images: ["doctor-male", "doctor-female"], 
  },
  
  { 
    name: 'Vigilante', 
    key: 'vigilante', 
    color: '#C5BFB1', 
    ability: 'Ever inconspicuous, the Vigilante strikes from the cover of night to eliminate one player, and one player only. <span>May their aim be true.</span>', 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: null, 
    assigned: false, 
    expansionRole: false, 
    enabled: true, 
    images: ["vigilante-male", "vigilante-female"], 
  },
  
  { 
    name: 'Mimic', 
    key: 'mimic', 
    color: '#D690B1', 
    ability: 'Mimic chooses a player during the first night and morphs into their role for the game. If Mimic selects a Werewolf, they become a Vigilante.', 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: null, 
    assigned: false, 
    expansionRole: true, 
    enabled: true, 
    images: ["mimic-male", "mimic-female"], 
  },
  
  { 
    name: 'Mayor', 
    key: 'mayor', 
    color: '#63A5B4', 
    ability: "The Mayor sways the votes to make their own count twice, but in doing so reveals their role. <span>Will they earn a target on their back?</span>", 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: 'voting', 
    assigned: false, 
    expansionRole: true, 
    enabled: true, 
    images: ["mayor-male", "mayor-female"], 
  },
  
  { 
    name: 'Medium', 
    key: 'medium', 
    color: '#B9B5B2', 
    ability: 'Medium sees dead chat at all times, but cannot communicate back. If medium dies, they may send one final message to a living player.', 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: null, 
    assigned: false, 
    expansionRole: true, 
    enabled: true, 
    images: ["medium-male", "medium-female"], 
  },
  
  { 
    name: 'Bodyguard', 
    key: 'bodyguard', 
    color: '#7C6860', 
    ability: 'Bodyguard chooses a player to protect each night. If that player is attacked, the attacker is killed. May only save one player per game.', 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: 'nightly', 
    assigned: false, 
    expansionRole: true, 
    enabled: true, 
    images: ["bodyguard-male", "bodyguard-female"], 
  },
  
  { 
    name: 'Overworked Investigator', 
    key: 'overworked-investigator', 
    color: '#C8A887', 
    ability: 'Fueled by caffiene and takeout food, Overworked Investigator works through the night once per game to learn the specific role of two players.', 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: 'nightly', 
    assigned: false, 
    expansionRole: true, 
    enabled: true, 
    images: ["overworked_investigator-male", "overworked_investigator-female"], 
  },
  
  { 
    name: 'Rogue', 
    key: 'rogue', 
    color: '#92BD76', 
    ability: 'Keen and distrusting, Rogue follows one player each night. The first time the player they follow attacks them, they survive and their attacker is eliminated.', 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: 'nightly', 
    assigned: false, 
    expansionRole: true, 
    enabled: true, 
    images: ["rogue-male", "rogue-female"], 
  },
  
  { 
    name: 'Witch Doctor', 
    key: 'witch-doctor', 
    color: '#f37246', 
    ability: 'A keeper of forbidden knowledge, the Witch Doctor may conduct an ancient ritual one night per game to return a player from the valley of death.', 
    winCondition: 'Eliminate Werewolves to save town.', 
    reminder: 'nightly', 
    assigned: false, 
    expansionRole: true, 
    enabled: true, 
    images: ["witch_doctor-male", "witch_doctor-female"], 
  },
  
  { 
    name: 'Jester', 
    key: 'jester', 
    color: '#A781B4', 
    ability: "Jesters are neither resident nor werewolf. <span>Are they even human?</span> Just try not to trust these tricksters; they'll totally turn the town into a circus of circular insanity.", 
    winCondition: 'Get voted out.', 
    reminder: null, 
    assigned: false, 
    expansionRole: true, 
    enabled: true, 
    images: ["jester-male", "jester-female"], 
  },
];